### ISSUE TITLE
Issue #0 - Wiki Home Page

### ISSUE THREAD

**Issue by keginzburg** [ncioffi1/webium#1]
# Wiki Home Page
- [X] Is the first page you see upon entering the wiki
- [X] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [X] All links in the right sidebar should contain each wiki page and link to the correct page
- [X] Correctly formatted
  - [X] each wiki page is listed in bullet points
  - [ ] all links route the correct page

## Comments
1. Just make sure to add a placeholder live link and set your bullets as links to your Design Document pages as well.

**Comment by ncioffi1** [comment]
> added placeholder link to live page
> made bullets links to design doc. pages
