### ISSUE TITLE
Issue #1 - Feature List

### ISSUE THREAD

**Issue by keginzburg** [ncioffi1/webium#2]
# Feature List
- [ ] Should have 7 Features.
  - [ ] 3 of those are User Auth, Render, and Production README.
  - [ ] The other 4 are from the [Feature List](https://github.com/appacademy/cohort-resources/blob/master/full_stack_projects/mvp_guidelines.md) or your PM will have clarified them with you.
- [X] Contains a description sentence of the app
- [ ] Includes two to three detailed bullets on functionality and presentation of feature
- [X] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [ ] Estimates how long it will take the code each Feature
- [ ] Correctly formatted
  - [ ] Features are listed in an ordered list
  - [ ] Each Feature is broken down into bullet points

## Comments
Hey Nick, this document needs some work.

1. First off, the formatting is a bit plain and could use some markdown syntax to separate Feature titles from their sub points. Leverage your headers, bullets, etc.

2. In terms of absolutely required Features, you have Heroku and User Auth listed, but you neglected to add a Production README as a Feature.

3. For your main Features, you listed Home, Create Article, Published Article as 3 separate Features when that would actually be one. For example: **Articles CRUD - Users can post, edit, or delete their articles with a title and basic formatting. Other users can see those articles within the main feed or their Following feed if they follow that author.**

4. Besides Articles, I recommend you list Comments (CRUD), Follows (CRD), and Likes (CRD) as your next three Features.

5. As for your Bonuses, adding ChatGPT generated articles is fine, but I recommend adding more functionality on top of the 4 main Features. For example, making Likes a full CRUD feature, so users can "clap" repeatedly for Articles is great. Or Bookmarks, Category Feeds, or Tags will suffice.

**Comment by ncioffi1** [comment]
> fixed formatting
> added Production README as a feature
> changed features to reflect CRUD concepts
> consolidated Article bullets into one Feature
> added more bonuses
