### ISSUE TITLE
Issue #2 - Database Schema

### ISSUE THREAD

**Issue by keginzburg** [ncioffi1/webium#3]
# Database Schema
- [X] Contains correct datatypes
- [X] Contains appropriate constraints/details
  - [ ] primary key
  - [X] not null
  - [ ] unique
  - [X] indexed
  - [X] foreign key
- [X] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [ ] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [X] Correctly formatted
  - [X] schema is written in a table format
  - [ ] the table's name are lowercased, snake_cased and `back_ticked`
  - [X] the table header column names are bolded
  - [ ] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
1. Does the `session_token` need to be indexed with uniqueness in the `users` table?
2. For now, our `articles` table is pretty spare. Medium does have an extensive Story editor to allow users to change format and add media wherever they want in the layout. We're not going to pursue that as its out of scope and could take 2 weeks to design on its own. Instead, we're going to opt to allow users to attach a single photo to their articles to start. To do so, we're going to utilize AWS down the line and the use of an ActiveStorage table. Let me know if you'd like to discuss later.
3. For our `claps` table, I recommend utilizing Polymorphic Associations so a clap can be associated with either an article or comment.

**Comment by ncioffi1** [comment]
> added uniqueness to session_token in users table
> added photo_id column to articles schema (not sure how i would implement this properly yet as am not familiar with AWS / photo storage, let me know if this is sufficient or if it needs to be a link or something instead)
> added polymorphic association instead of two foreign keys of article / comment
