### ISSUE TITLE
Issue #3 - Sample State

### ISSUE THREAD

**Issue by keginzburg** [ncioffi1/webium#4]
# Sample State
- [X] State shape is flat!
- [X] State's keys are camelCased
- [X] All keys within the values in the state are accessible in the schema
- [X] Correctly formatted
  - [X] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [X] Top level slices
    - [X] `entities`
    - [ ] `session`
    - [ ] `errors` (here or in `ui`)
    - [ ] `ui` (if needed)
  - [X] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can't change
    + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
1. Let's make sure to add relevant top slices of state: `session`, `ui`, `errors`.
2. Your claps hold foreign keys to both comments and articles. Again, I recommend utilizing polymorphic associations, but we can discuss this down the line.

**Comment by ncioffi1** [comment]
> added top slices of state - session, ui, errors (not entirely sure at the moment what errors to put so I just have a basic login error for now)
> edited claps section to reflect polymorphic associations
