### ISSUE TITLE
Issue #4 - Backend Routes

### ISSUE THREAD

**Issue by keginzburg** [ncioffi1/webium#5]
# Backend Routes
- [ ] Contains the following sections: HTML, API Endpoints(Backend)
- [X] Each route has a description
- [X] API Endpoint routes contains wildcard variables written in `snake_case`
- [X] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [X] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
1. Don't forget the `GEt /api/session` route for the purpose of restoring the session for the frontend component tree and Redux session slice.
2. Will we need a route to fetch all of our articles? If so, will this need to parse search params as well?
3. Comments will be a CRUD cycle, so you should also be able to `PATCH` them.

**Comment by ncioffi1** [comment]
> added GET /api/session route
> added route to fetch all articles (index route)
> added PATCH route for comments
