### ISSUE TITLE
Issue #5 - Frontend Routes

### ISSUE THREAD

**Issue by keginzburg** [ncioffi1/webium#6]
# Frontend Routes
- [X] Frontend routes contains wildcard variables written in `camelCase`
- [X] Correctly formatted
  - [X] Routes are displayed with `inline coding text` (backticks)

## Comments
1. I recommend structuring your frontend routes with less dynamic segments. There's nothing wrong with integrating them and using them to pull the correct information from your backend, but we could benefit by making our `<ProfileForm />` render at `/users/:id` as opposed to `/:username`.
2. Keep hashing this out a bit. We want it to serve as a nice base when we get to our UI down the line.

**Comment by ncioffi1** [comment]
> changed routes to be less dynamic
